spring:
  datasource:
    hikari:
      max-lifetime: 177000
    url: jdbc:mysql://localhost:3306/poker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: chan
    password: chan1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate.format_sql: true

server:
  servlet:
    context-path: /backend
    cookie:
      same-site: None
      secure: true

file: ./UserImage

springdoc:
  show-login-endpoint: true
#logging:
#  level:
#    web: debug
